version: "2"
services:
  app:
    container_name: product-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - product-db
  product-db:
    container_name: product-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

